/*
 * This file is generated by jOOQ.
 */
package src.main.java.com.nokri.dao;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import src.main.java.com.nokri.dao.tables.Education;
import src.main.java.com.nokri.dao.tables.FlywaySchemaHistory;
import src.main.java.com.nokri.dao.tables.Job;
import src.main.java.com.nokri.dao.tables.Project;
import src.main.java.com.nokri.dao.tables.User;
import src.main.java.com.nokri.dao.tables.UserJob;
import src.main.java.com.nokri.dao.tables.Userprofile;
import src.main.java.com.nokri.dao.tables.WorkExperience;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.education</code>.
     */
    public final Education EDUCATION = Education.EDUCATION;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.job</code>.
     */
    public final Job JOB = Job.JOB;

    /**
     * The table <code>public.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.user_job</code>.
     */
    public final UserJob USER_JOB = UserJob.USER_JOB;

    /**
     * The table <code>public.userprofile</code>.
     */
    public final Userprofile USERPROFILE = Userprofile.USERPROFILE;

    /**
     * The table <code>public.work_experience</code>.
     */
    public final WorkExperience WORK_EXPERIENCE = WorkExperience.WORK_EXPERIENCE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Education.EDUCATION,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Job.JOB,
            Project.PROJECT,
            User.USER,
            UserJob.USER_JOB,
            Userprofile.USERPROFILE,
            WorkExperience.WORK_EXPERIENCE
        );
    }
}
