/*
 * This file is generated by jOOQ.
 */
package src.main.java.com.nokri.dao;


import src.main.java.com.nokri.dao.tables.Education;
import src.main.java.com.nokri.dao.tables.FlywaySchemaHistory;
import src.main.java.com.nokri.dao.tables.Job;
import src.main.java.com.nokri.dao.tables.Project;
import src.main.java.com.nokri.dao.tables.User;
import src.main.java.com.nokri.dao.tables.UserJob;
import src.main.java.com.nokri.dao.tables.Userprofile;
import src.main.java.com.nokri.dao.tables.WorkExperience;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.education</code>.
     */
    public static final Education EDUCATION = Education.EDUCATION;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.job</code>.
     */
    public static final Job JOB = Job.JOB;

    /**
     * The table <code>public.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_job</code>.
     */
    public static final UserJob USER_JOB = UserJob.USER_JOB;

    /**
     * The table <code>public.userprofile</code>.
     */
    public static final Userprofile USERPROFILE = Userprofile.USERPROFILE;

    /**
     * The table <code>public.work_experience</code>.
     */
    public static final WorkExperience WORK_EXPERIENCE = WorkExperience.WORK_EXPERIENCE;
}
