/*
 * This file is generated by jOOQ.
 */
package src.main.java.com.nokri.dao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.com.nokri.dao.tables.Userprofile;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserprofileRecord extends UpdatableRecordImpl<UserprofileRecord> implements Record10<Long, Long, String, String, String, String, Integer, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.userprofile.profile_id</code>.
     */
    public void setProfileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.userprofile.profile_id</code>.
     */
    public Long getProfileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.userprofile.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.userprofile.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.userprofile.objective</code>.
     */
    public void setObjective(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.userprofile.objective</code>.
     */
    public String getObjective() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.userprofile.country</code>.
     */
    public void setCountry(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.userprofile.country</code>.
     */
    public String getCountry() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.userprofile.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.userprofile.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.userprofile.street</code>.
     */
    public void setStreet(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.userprofile.street</code>.
     */
    public String getStreet() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.userprofile.zipcode</code>.
     */
    public void setZipcode(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.userprofile.zipcode</code>.
     */
    public Integer getZipcode() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.userprofile.linkedin_url</code>.
     */
    public void setLinkedinUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.userprofile.linkedin_url</code>.
     */
    public String getLinkedinUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.userprofile.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.userprofile.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.userprofile.contact_no</code>.
     */
    public void setContactNo(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.userprofile.contact_no</code>.
     */
    public Integer getContactNo() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, String, String, String, String, Integer, String, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, String, String, String, String, Integer, String, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Userprofile.USERPROFILE.PROFILE_ID;
    }

    @Override
    public Field<Long> field2() {
        return Userprofile.USERPROFILE.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Userprofile.USERPROFILE.OBJECTIVE;
    }

    @Override
    public Field<String> field4() {
        return Userprofile.USERPROFILE.COUNTRY;
    }

    @Override
    public Field<String> field5() {
        return Userprofile.USERPROFILE.CITY;
    }

    @Override
    public Field<String> field6() {
        return Userprofile.USERPROFILE.STREET;
    }

    @Override
    public Field<Integer> field7() {
        return Userprofile.USERPROFILE.ZIPCODE;
    }

    @Override
    public Field<String> field8() {
        return Userprofile.USERPROFILE.LINKEDIN_URL;
    }

    @Override
    public Field<String> field9() {
        return Userprofile.USERPROFILE.COUNTRY_CODE;
    }

    @Override
    public Field<Integer> field10() {
        return Userprofile.USERPROFILE.CONTACT_NO;
    }

    @Override
    public Long component1() {
        return getProfileId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getObjective();
    }

    @Override
    public String component4() {
        return getCountry();
    }

    @Override
    public String component5() {
        return getCity();
    }

    @Override
    public String component6() {
        return getStreet();
    }

    @Override
    public Integer component7() {
        return getZipcode();
    }

    @Override
    public String component8() {
        return getLinkedinUrl();
    }

    @Override
    public String component9() {
        return getCountryCode();
    }

    @Override
    public Integer component10() {
        return getContactNo();
    }

    @Override
    public Long value1() {
        return getProfileId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getObjective();
    }

    @Override
    public String value4() {
        return getCountry();
    }

    @Override
    public String value5() {
        return getCity();
    }

    @Override
    public String value6() {
        return getStreet();
    }

    @Override
    public Integer value7() {
        return getZipcode();
    }

    @Override
    public String value8() {
        return getLinkedinUrl();
    }

    @Override
    public String value9() {
        return getCountryCode();
    }

    @Override
    public Integer value10() {
        return getContactNo();
    }

    @Override
    public UserprofileRecord value1(Long value) {
        setProfileId(value);
        return this;
    }

    @Override
    public UserprofileRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserprofileRecord value3(String value) {
        setObjective(value);
        return this;
    }

    @Override
    public UserprofileRecord value4(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public UserprofileRecord value5(String value) {
        setCity(value);
        return this;
    }

    @Override
    public UserprofileRecord value6(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public UserprofileRecord value7(Integer value) {
        setZipcode(value);
        return this;
    }

    @Override
    public UserprofileRecord value8(String value) {
        setLinkedinUrl(value);
        return this;
    }

    @Override
    public UserprofileRecord value9(String value) {
        setCountryCode(value);
        return this;
    }

    @Override
    public UserprofileRecord value10(Integer value) {
        setContactNo(value);
        return this;
    }

    @Override
    public UserprofileRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Integer value7, String value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserprofileRecord
     */
    public UserprofileRecord() {
        super(Userprofile.USERPROFILE);
    }

    /**
     * Create a detached, initialised UserprofileRecord
     */
    public UserprofileRecord(Long profileId, Long userId, String objective, String country, String city, String street, Integer zipcode, String linkedinUrl, String countryCode, Integer contactNo) {
        super(Userprofile.USERPROFILE);

        setProfileId(profileId);
        setUserId(userId);
        setObjective(objective);
        setCountry(country);
        setCity(city);
        setStreet(street);
        setZipcode(zipcode);
        setLinkedinUrl(linkedinUrl);
        setCountryCode(countryCode);
        setContactNo(contactNo);
    }
}
